name: Deploy to VM10

on:
  push:
    branches:
      - Dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Repository klonen
        uses: actions/checkout@v3

      - name: Set SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VM_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add VM host to known_hosts
        run: |
          ssh-keyscan vm10.htl-leonding.ac.at >> ~/.ssh/known_hosts

      - name: Java installieren
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Projekt bauen
        run: |
          cd backend_v2
          ./mvnw package -DskipTests

      - name: JAR auf VM kopieren
        run: |
          scp -o StrictHostKeyChecking=no backend_v2/target/*.jar veladm@vm10.htl-leonding.ac.at:/home/veladm/d4d/app.jar
          

      - name: docker-compose auf VM kopieren
        run: |
          scp -o StrictHostKeyChecking=no docker-compose.yaml veladm@vm10.htl-leonding.ac.at:/home/veladm/d4d/docker-compose.yaml
